const USER_CREATE = 'USER_CREATE';
const USER_DELETE = 'USER_DELETE';
const USER_LIST = 'USER_LIST'
const USER_LIST_FILTER = 'USER_LIST_FILTER';
const GET_USERS_LIST = 'GET_USERS_LIST'

const types = {
    USER_CREATE,
    USER_DELETE,
    USER_LIST,
    USER_LIST_FILTER,
    GET_USERS_LIST
}

export default types