const CAR_CREATE = 'CAR_CREATE';
const CAR_DELETE = 'CAR_DELETE';
const CAR_LIST = 'CAR_LIST'
const CAR_LIST_FILTER = 'CAR_LIST_FILTER';
const CAR_LIST_SORT = 'CAR_LIST_SORT';
const CAR_EDIT = 'CAR_EDIT'
const GET_CARS_LIST = 'GET_CARS_LIST';
const types = {
    CAR_CREATE,
    CAR_DELETE,
    CAR_EDIT,
    CAR_LIST,
    CAR_LIST_FILTER,
    CAR_LIST_SORT,
    GET_CARS_LIST
}

export default types